default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
development:
  <<: *default
  database: journal_app
test:
  <<: *default
  database: test_app_db_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  
cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
